---
functional:
  - Пользователь может просматривать карточки товара (подробное описания товара)
  - Пользователь может найти товар по ключевому слову
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру, марке, модели и категории 
  - Пользователь может сбросить выбранную категорию товаров
  - Товар можно сортировать по наличию в магазине 
  - Пользователь может добавлять товар в корзину из карточки товара и каталога 
  - Пользователь может изменять количество товаров - добавлять или удалять их
  - Пользователь имеет возможность перейти в корзину на любом этапе
  - Из корзины можно удалить всё
  - Пользователь может оформить заказ из корзины 
  - Заказ может оформить только зарегистрированный пользователь 
  - Корзина должна хранится в сессии браузера
  - Наличие кнопок для перемещения по страницам товаров 
  - Кнопка вверх для прокрутки страницы сайта в начало
non-functional:
  - Требуется постоянное наличие шапки сайта 
  - Отображение в корзине товаров их название, рейтинг, цена со скидкой и цена без скидки 
  - Отображение уведомления о том, что товар успешно добавлен 
  - Общая стоимость в корзине отображается корректно
  - Цена отображается корректно с учетом скидки 
  - При переходе с одной страницы магазина на другую не происходит перезагрузка - магазин является SPA приложением
  - Веб-сайт должен быть адаптивным 
  - Веб-сайт должен быть кроссбраузерным
implicit:
  - На главной странице должна быть реализована кнопка для входа в аккаунт
  - При открытии главной страницы должно отображаться меню сайта, где товары поделены на категории - смартфоны, ноутбуки, ароматы, средства для ухода за кожей, бакалея, предметы интерьера и скидки
  - Требуется авторизация для создания заказа
  - Форма авторизации содержит поля для ввода логина и пароля, кнопку войти
  - Требуется регистрация, если еще не создан аккаунт
  - В форме регистрации отображаются поля с вводом имени, фамилии, логина, e-mail, номера телефона, пароля и подтверждение пароля, а также кнопка зарегистрироваться
  - Все поля в форме регистрации обязательны для заполнения и не могут быть пустыми
  - Выводить сообщения при регистрации и авторизации о том, что поле обязательно к заполнению
  - Кнопка регистрации не активна пока все поля не будут корректно заполнены
  - Проверяется e-mail на корректность
  - Имя пользователя должно быть не короче двух символов
  - Имя пользователя не должно быть длиннее 25 символов
  - Фамилия пользователя должна быть не короче 2 символов
  - Фамилия пользователя должна быть не длиннее 30 символов
  - Номер телефона пользователя должен начинаться на + или 8 
  - Пароль должен быть не меньше 6 символом
  - Пароль должен содержать спец символы
  - Пароль должен быть введен только латиницей 
  - Пароль должен содержать минимум 1 большую букву
  - Пароль должен содержать минимум 1 цифру 
  - После регистрации появляется сообщение об успешной регистрации
  - Пользователя после успешной регистрации перенаправляет на страницу оформления заказа
  - Пользователь может просмотреть историю заказов 
  - Если товара нет в наличии, то его нельзя добавить в корзину и об этом появляется уведомление